#!/bin/bash

filePath=files/*

for file in $filePath
    do

    for i in A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
    do
        if [[ ${file##*/} =~ ^$i ]]; then
            mv $file ${i,,}
        fi
    done

    for i in a b c d e f g h i j k l m n o p q r s t u v w x y z
    do
        if [[ ${file##*/} =~ ^$i ]]; then
            mv $file ${i,,}
        fi
    done
done